apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-sekhar
  labels:
    app: flask-app
spec:
  replicas: 1  # Number of pod replicas
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app-container
        image: us.gcr.io/ferrous-upgrade-446608-k0/sekhar-prince:latest
        ports:
        - containerPort: 5000  # Change this to the port your application listens on
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: LoadBalancer  # Expose the service externally
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 80       # Port for external access
    targetPort: 5000  # Port your application listens on in the container
