---
- name: Install Nginx on Debian-based systems
  hosts: webservers
  become: yes
  tasks:

    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx is running and enabled at boot
      service:
        name: nginx
        state: started
        enabled: yes
